=== cpythoud/beanmaker-v2-cli/src/main/resources/beanmaker-table.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://schema.beanmaker.org/beanmaker-table"
           xmlns="https://schema.beanmaker.org/beanmaker-table"
           elementFormDefault="qualified"
>
    <xs:element name="table">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="package" type="xs:string"/>
                <xs:element name="bean" type="xs:string"/>
                <xs:element name="fields" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="field" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="sql-name" type="xs:string"/>
                                        <xs:element name="java-type" type="xs:string"/>
                                        <xs:element name="java-name" type="xs:string"/>
                                        <xs:element name="required" type="xs:boolean"/>
                                        <xs:element name="unique" type="xs:boolean"/>
                                        <xs:element name="decimals" type="xs:integer" minOccurs="0"/>
                                        <xs:element name="positive-only" type="xs:boolean" minOccurs="0"/>
                                        <xs:element name="bean-class" type="xs:string" minOccurs="0"/>
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="item-order-associated-field" minOccurs="0"/>
                <xs:element name="relationships" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="relationship" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="database-table" type="xs:string"/>
                                        <xs:element name="java-type" type="xs:string"/>
                                        <xs:element name="java-name" type="xs:string"/>
                                        <xs:element name="id-field" type="xs:string"/>
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="extra-fields" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="field" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="java-type" type="xs:string"/>
                                        <xs:element name="java-name" type="xs:string"/>
                                        <xs:element name="initialization" type="xs:string" minOccurs="0"/>
                                        <xs:element name="final" minOccurs="0">
                                            <xs:complexType/>
                                        </xs:element>
                                        <xs:element name="imports" minOccurs="0" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="import" type="xs:string" maxOccurs="unbounded"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== cpythoud/beanmaker-v2-cli/src/main/design/beanmaker.dot/invoices.xml
<?xml version="1.0" encoding="UTF-8" ?>
<table xmlns="https://schema.beanmaker.org/beanmaker-table"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="https://schema.beanmaker.org/beanmaker-table ../../resources/beanmaker-table.xsd"
>
    <name>invoices</name>
    <package>ch.abcis.dbtest</package>
    <bean>Invoice</bean>
    <fields>
        <field>
            <sql-name>id_customer</sql-name>
            <java-type>long</java-type>
            <java-name>idCustomer</java-name>
            <required>true</required>
            <unique>false</unique>
            <bean-class>Customer</bean-class>
        </field>
        <field>
            <sql-name>number</sql-name>
            <java-type>String</java-type>
            <java-name>number</java-name>
            <required>true</required>
            <unique>true</unique>
        </field>
        <field>
            <sql-name>printed_date</sql-name>
            <java-type>Date</java-type>
            <java-name>printedDate</java-name>
            <required>true</required>
            <unique>false</unique>
        </field>
    </fields>
    <relationships>
        <relationship>
            <database-table>items</database-table>
            <java-type>Item</java-type>
            <java-name>items</java-name>
            <id-field>id_invoice</id-field>
        </relationship>
    </relationships>
</table>

=== cpythoud/beanmaker-v2-cli/src/main/design/beanmaker.dot/categories.xml
<?xml version="1.0" encoding="UTF-8" ?>
<table xmlns="https://schema.beanmaker.org/beanmaker-table"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="https://schema.beanmaker.org/beanmaker-table ../../resources/beanmaker-table.xsd"
>
    <name>categories</name>
    <package>ch.abcis.dbtest</package>
    <bean>Category</bean>
    <fields>
        <field>
            <sql-name>id_label</sql-name>
            <java-type>long</java-type>
            <java-name>idLabel</java-name>
            <required>true</required>
            <unique>false</unique>
            <bean-class>DbBeanLabel</bean-class>
        </field>
    </fields>
    <relationships>
        <relationship>
            <database-table>products</database-table>
            <java-type>Product</java-type>
            <java-name>products</java-name>
            <id-field>id_category</id-field>
        </relationship>
    </relationships>
</table>

=== cpythoud/beanmaker-v2-cli/src/main/design/beanmaker.dot/items.xml
<?xml version="1.0" encoding="UTF-8" ?>
<table xmlns="https://schema.beanmaker.org/beanmaker-table"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="https://schema.beanmaker.org/beanmaker-table ../../resources/beanmaker-table.xsd"
>
    <name>items</name>
    <package>ch.abcis.dbtest</package>
    <bean>Item</bean>
    <fields>
        <field>
            <sql-name>id_invoice</sql-name>
            <java-type>long</java-type>
            <java-name>idInvoice</java-name>
            <required>true</required>
            <unique>false</unique>
            <bean-class>Invoice</bean-class>
        </field>
        <field>
            <sql-name>qty</sql-name>
            <java-type>Integer</java-type>
            <java-name>qty</java-name>
            <required>true</required>
            <unique>false</unique>
        </field>
        <field>
            <sql-name>description</sql-name>
            <java-type>String</java-type>
            <java-name>description</java-name>
            <required>true</required>
            <unique>false</unique>
        </field>
        <field>
            <sql-name>unit_price</sql-name>
            <java-type>Money</java-type>
            <java-name>unitPrice</java-name>
            <required>true</required>
            <unique>false</unique>
        </field>
    </fields>
    <item-order-associated-field>id_invoice</item-order-associated-field>
</table>

=== cpythoud/beanmaker-v2-cli/src/main/design/beanmaker.dot/brochures.xml
<?xml version="1.0" encoding="UTF-8" ?>
<table xmlns="https://schema.beanmaker.org/beanmaker-table"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="https://schema.beanmaker.org/beanmaker-table ../../resources/beanmaker-table.xsd"
>
    <name>brochures</name>
    <package>ch.abcis.dbtest</package>
    <bean>Brochure</bean>
    <fields>
        <field>
            <sql-name>published_on</sql-name>
            <java-type>Date</java-type>
            <java-name>publishedOn</java-name>
            <required>true</required>
            <unique>false</unique>
        </field>
        <field>
            <sql-name>id_file</sql-name>
            <java-type>long</java-type>
            <java-name>idFile</java-name>
            <required>true</required>
            <unique>false</unique>
            <bean-class>DbBeanFile</bean-class>
        </field>
    </fields>
</table>

=== cpythoud/beanmaker-v2-cli/src/main/design/beanmaker.dot/appointments.xml
<?xml version="1.0" encoding="UTF-8" ?>
<table xmlns="https://schema.beanmaker.org/beanmaker-table"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="https://schema.beanmaker.org/beanmaker-table ../../resources/beanmaker-table.xsd"
>
    <name>appointment</name>
    <package>ch.abcis.dbtest</package>
    <bean>Appointment</bean>
    <fields>
        <field>
            <sql-name>with_whom</sql-name>
            <java-type>String</java-type>
            <java-name>withWhom</java-name>
            <required>true</required>
            <unique>false</unique>
        </field>
        <field>
            <sql-name>when</sql-name>
            <java-type>Timestamp</java-type>
            <java-name>when</java-name>
            <required>true</required>
            <unique>false</unique>
        </field>
        <field>
            <sql-name>end_of_meeting</sql-name>
            <java-type>Time</java-type>
            <java-name>endOfMeeting</java-name>
            <required>true</required>
            <unique>false</unique>
        </field>
        <field>
            <sql-name>ok_to_be_late</sql-name>
            <java-type>Boolean</java-type>
            <java-name>okToBeLate</java-name>
            <required>true</required>
            <unique>false</unique>
        </field>
    </fields>
</table>

=== cpythoud/beanmaker-v2-cli/src/main/design/beanmaker.dot/table1_name.xml
<table xmlns="https://schema.beanmaker.org/beanmaker-table"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="https://schema.beanmaker.org/beanmaker-table ../../resources/beanmaker-table.xsd"
>
    <name>table-name</name>
    <package>com.java.package</package>
    <bean>BeanClassName</bean>
    <!-- showing only fields with non default configuration -->
    <fields>
        <field>
            <sql-name>id_customer</sql-name>
            <java-type>long</java-type>
            <java-name>idCustomer</java-name>
            <required>true</required>
            <unique>false</unique>
            <bean-class>Customer</bean-class>
        </field>
        <field>
            <sql-name>number</sql-name>
            <java-type>String</java-type>
            <java-name>number</java-name>
            <required>true</required>
            <unique>false</unique>
        </field>
        <field>
            <sql-name>printed_date</sql-name>
            <java-type>Date</java-type>
            <java-name>printedDate</java-name>
            <required>true</required>
            <unique>false</unique>
        </field>
    </fields>
    <relationships>
        <relationship>
            <database-table>items</database-table>
            <java-type>Item</java-type>
            <java-name>items</java-name>
            <id-field>id_invoice</id-field>
            <list-only>true</list-only>
        </relationship>
    </relationships>
    <extra-fields>
        <field>
            <java-type>MyType</java-type>
            <java-name>myTypeObject</java-name>
            <initialisation>new MyType(OtherType.CONSTANT)</initialisation>
            <final/>
            <import>com.company.software.MyType</import>
            <import>com.company.software.OtherType</import>
        </field>
        <field>
            <java-type>OtherType</java-type>
            <java-name>otherTypeObject</java-name>
            <initialisation>new OtherType()</initialisation>
            <final/>
        </field>
    </extra-fields>
</table>

=== cpythoud/beanmaker-v2-cli/src/main/design/beanmaker.dot/customers.xml
<?xml version="1.0" encoding="UTF-8" ?>
<table xmlns="https://schema.beanmaker.org/beanmaker-table"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="https://schema.beanmaker.org/beanmaker-table ../../resources/beanmaker-table.xsd"
>
    <name>customers</name>
    <package>ch.abcis.dbtest</package>
    <bean>Customer</bean>
    <fields>
        <field>
            <sql-name>name</sql-name>
            <java-type>String</java-type>
            <java-name>name</java-name>
            <required>true</required>
            <unique>false</unique>
        </field>
        <field>
            <sql-name>tex_name</sql-name>
            <java-type>String</java-type>
            <java-name>texName</java-name>
            <required>true</required>
            <unique>true</unique>
        </field>
    </fields>
    <relationships>
        <relationship>
            <database-table>invoices</database-table>
            <java-type>Invoice</java-type>
            <java-name>invoices</java-name>
            <id-field>id_customer</id-field>
        </relationship>
    </relationships>
</table>

=== cpythoud/beanmaker-v2-cli/src/main/design/beanmaker.dot/products.xml
<?xml version="1.0" encoding="UTF-8" ?>
<table xmlns="https://schema.beanmaker.org/beanmaker-table"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="https://schema.beanmaker.org/beanmaker-table ../../resources/beanmaker-table.xsd"
>
    <name>products</name>
    <package>ch.abcis.dbtest</package>
    <bean>Product</bean>
    <fields>
        <field>
            <sql-name>id_category</sql-name>
            <java-type>long</java-type>
            <java-name>idCategory</java-name>
            <required>true</required>
            <unique>false</unique>
            <bean-class>Category</bean-class>
        </field>
        <field>
            <sql-name>id_label</sql-name>
            <java-type>long</java-type>
            <java-name>idLabel</java-name>
            <required>true</required>
            <unique>false</unique>
            <bean-class>DbBeanLabel</bean-class>
        </field>
        <field>
            <sql-name>id_description_label</sql-name>
            <java-type>long</java-type>
            <java-name>idDescriptionLabel</java-name>
            <required>true</required>
            <unique>false</unique>
            <bean-class>DbBeanLabel</bean-class>
        </field>
        <field>
            <sql-name>id_replaced_product</sql-name>
            <java-type>long</java-type>
            <java-name>idReplacedProduct</java-name>
            <required>false</required>
            <unique>false</unique>
            <bean-class>Product</bean-class>
        </field>
    </fields>
</table>
